spring.datasource.url=${jdbc:postgresql://dpg-d9q8rhu1egvs73dh9icg-a/ats_db_5rp7}
spring.datasource.username=${ats_db_5rp7_user}
spring.datasource.password=${ojcDFPtGefe2Z8ZsV3gQOpwmXrDtKYv2}
spring.jpa.hibernate.ddl-auto=update